[project]
name = "doc-summary-llm-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "huggingface-hub>=1.31.0",
    "kiwipiepy>=0.23.2",
    "ollama>=0.6.2",
    "openai>=3.14.1",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "rouge-score>=0.1.2",
]
